/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addSampleServices' : IDL.Func([], [], []),
  'getCompanyInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'name' : IDL.Text,
          'description' : IDL.Text,
          'address' : IDL.Text,
          'phone' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getService' : IDL.Func([IDL.Nat], [Service], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'updateCompanyInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addSampleServices' : IDL.Func([], [], []),
    'getCompanyInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'name' : IDL.Text,
            'description' : IDL.Text,
            'address' : IDL.Text,
            'phone' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getService' : IDL.Func([IDL.Nat], [Service], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'updateCompanyInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };